### ISSUE TITLE
Package install failed

### ISSUE THREAD

**Issue by outOFFspace** [DevGroup-ru/yii2-multilingual#15]
Problem 1
    - devgroup/yii2-multilingual 0.1.0 requires devgroup/yii2-tag-dependency-helper ~1.4.0 -> satisfiable by devgroup/yii2-tag-dependency-helper[1.4.0].
    - devgroup/yii2-multilingual dev-context requires devgroup/yii2-tag-dependency-helper ~1.4.0 -> satisfiable by devgroup/yii2-tag-dependency-helper[1.4.0].
    - devgroup/yii2-multilingual dev-master requires devgroup/yii2-tag-dependency-helper ~1.4.0 -> satisfiable by devgroup/yii2-tag-dependency-helper[1.4.0].
    - Conclusion: don't install devgroup/yii2-tag-dependency-helper 1.4.0
    - Installation request for devgroup/yii2-multilingual \* -> satisfiable by devgroup/yii2-multilingual[0.1.0, dev-context, dev-master].

**Comment by bethrezen** [comment]
0.1.0 version is broken, please use dev-master

**Comment by outOFFspace** [comment]
Another problem with dev-master:
Problem 1
    - Can only install one of: devgroup/yii2-tag-dependency-helper[1.4.0, 0.0.3].
    - Can only install one of: devgroup/yii2-tag-dependency-helper[1.4.0, 0.0.3].
    - Can only install one of: devgroup/yii2-tag-dependency-helper[1.4.0, 0.0.3].
    - devgroup/yii2-multilingual dev-master requires devgroup/yii2-tag-dependency-helper ~1.4.0 -> satisfiable by devgroup/yii2-tag-dependency-helper[1.4.0].
    - Installation request for devgroup/yii2-multilingual dev-master -> satisfiable by devgroup/yii2-multilingual[dev-master].
    - Installation request for devgroup/yii2-tag-dependency-helper (locked at 0.0.3) -> satisfiable by devgroup/yii2-tag-dependency-helper[0.0.3].

**Comment by bethrezen** [comment]
remove composer.lock

**Comment by bethrezen** [comment]
or install devgroup/yii2-tag-dependency-helper:~1.4.0 manually
